name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd checker
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run check script to generate CSV
      run: |
        cd checker
        python check.py
    - name: Move the output.csv file to the data folder in viewer
      run: |
        mv output/output.csv viewer/data/

    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: npm install
      run: |
        cd viewer
        npm ci

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: |
        cd viewer
        hugo --minify
    - name: Setup dist folder for github.io
      run: |
        touch ./viewer/public/.nojekyll
        sed -i '/\/viewer/public/d' .gitignore
        echo "ncn-milepost-openstreetmap-checker.leifgehrmann.com" >> ./viewer/public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./viewer/public
        force_orphan: true
