name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run check script to generate CSV
      run: |
        python check.py
    - name: Convert CSV into a readable document
      run: |
        python render_csv_to_html.py
    - name: Setup dist folder for github.io
      run: |
        touch ./dist/.nojekyll
        sed -i '/\/dist/d' .gitignore
        echo "ncn-milepost-openstreetmap-checker.leifgehrmann.com" >> ./dist/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.6.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        forceOrphan: true
